import tkinter
from tkinter import messagebox

def student_details():
    master = tkinter.Tk()
    master.title("Student Profile")
    master.geometry('1370x760')
    master.configure(bg='light green')
    mainframe = tkinter.Frame(master, bg= "light green")
    mainframe.grid(row=0, column=0)
    # mainframe.grid(sticky="news")
    mainframe.grid(padx=400, pady=200)
    page3frame = tkinter.LabelFrame(mainframe, text="Student Information", bg='light yellow', cursor='star', fg="black", bd=10,  relief="groove")
    page3frame.grid(row=1, column=1)
    # page3frame.grid(padx=500, pady=100)
    name = tkinter.Label(page3frame, text="Name", bg="light yellow", fg="black")
    fname = tkinter.Label(page3frame, text="Father Name", bg="light yellow", fg="black")
    mname = tkinter.Label(page3frame, text="Mother Name", bg="light yellow", fg="black")
    address = tkinter.Label(page3frame, text="Address", bg="light yellow", fg="black")
    Mobilenum = tkinter.Label(page3frame, text="Mobile number", bg="light yellow", fg="black")
    email = tkinter.Label(page3frame, text="Email ID", bg="light yellow", fg="black")
    dob = tkinter.Label(page3frame, text="Date Of Birth", bg="light yellow", fg="black")
    gender = tkinter.Label(page3frame, text="Gender", bg="light yellow", fg="black")

    name.grid(row=0, column=0)
    fname.grid(row=1, column=0)
    mname.grid(row=2, column=0)
    address.grid(row=3, column=0)
    Mobilenum.grid(row=4, column=0)
    email.grid(row=5, column=0)
    dob.grid(row=6, column=0)
    gender.grid(row=7, column=0)

    name1 = tkinter.Entry(page3frame, font=("Arial", 16), bg="light yellow", fg="black")
    fname1 = tkinter.Entry(page3frame, font=("Arial", 16), bg="light yellow", fg="black")
    mname1 = tkinter.Entry(page3frame, font=("Arial", 16), bg="light yellow", fg="black")
    address1 = tkinter.Entry(page3frame, font=("Arial", 16), bg="light yellow", fg="black")
    Mobilenum1 = tkinter.Entry(page3frame, font=("Arial", 16), bg="light yellow", fg="black")
    emailid1 = tkinter.Entry(page3frame, font=("Arial", 16), bg="light yellow", fg="black")
    dob1 = tkinter.Entry(page3frame, font=("Arial", 16), bg="light yellow", fg="black")
    gender1 = tkinter.Entry(page3frame, font=("Arial", 16), bg="light yellow", fg="black")

    name1.grid(row=0, column=1)
    fname1.grid(row=1, column=1)
    mname1.grid(row=2, column=1)
    address1.grid(row=3, column=1)
    Mobilenum1.grid(row=4, column=1)
    emailid1.grid(row=5, column=1)
    dob1.grid(row=6, column=1)
    gender1.grid(row=7, column=1)

    buttonframe = tkinter.LabelFrame(mainframe, text="Options: ", bg='light yellow', fg="Black", cursor='star', bd=10, relief="groove")
    buttonframe.grid(row=2, column=1)
    save = tkinter.Button(buttonframe, text="Save", bg="light yellow", fg="black")
    display = tkinter.Button(buttonframe, text="Display", bg="light yellow", fg="black")
    reset = tkinter.Button(buttonframe, text="Reset", bg="light yellow", fg="black")
    update = tkinter.Button(buttonframe, text="Update", bg="light yellow", fg="black")
    delete = tkinter.Button(buttonframe, text="Delete", bg="light yellow", fg="black")
    search = tkinter.Button(buttonframe, text="Search", bg="light yellow", fg="black")
    exit = tkinter.Button(buttonframe, text="Exit", bg="light yellow", fg="black")

    save.grid(row=0, column=0)
    display.grid(row=0, column=1)
    reset.grid(row=0, column=2)
    update.grid(row=0, column=3)
    delete.grid(row=0, column=4)
    search.grid(row=0, column=5)
    exit.grid(row=0, column=6)

    master.mainloop()

